insert into public.us_states (code, name, dmv_supported, resources_supported, verified_at)
values
  ('AL', 'Alabama', false, false, null),
  ('AK', 'Alaska', false, false, null),
  ('AZ', 'Arizona', false, false, null),
  ('AR', 'Arkansas', false, false, null),
  ('CA', 'California', false, false, null),
  ('CO', 'Colorado', false, false, null),
  ('CT', 'Connecticut', false, false, null),
  ('DE', 'Delaware', false, false, null),
  ('FL', 'Florida', false, false, null),
  ('GA', 'Georgia', false, false, null),
  ('HI', 'Hawaii', false, false, null),
  ('ID', 'Idaho', false, false, null),
  ('IL', 'Illinois', false, false, null),
  ('IN', 'Indiana', false, false, null),
  ('IA', 'Iowa', false, false, null),
  ('KS', 'Kansas', false, false, null),
  ('KY', 'Kentucky', false, false, null),
  ('LA', 'Louisiana', false, false, null),
  ('ME', 'Maine', false, false, null),
  ('MD', 'Maryland', false, false, null),
  ('MA', 'Massachusetts', false, false, null),
  ('MI', 'Michigan', false, false, null),
  ('MN', 'Minnesota', false, false, null),
  ('MS', 'Mississippi', false, false, null),
  ('MO', 'Missouri', false, false, null),
  ('MT', 'Montana', false, false, null),
  ('NE', 'Nebraska', false, false, null),
  ('NV', 'Nevada', false, false, null),
  ('NH', 'New Hampshire', false, false, null),
  ('NJ', 'New Jersey', false, false, null),
  ('NM', 'New Mexico', false, false, null),
  ('NY', 'New York', false, false, null),
  ('NC', 'North Carolina', false, false, null),
  ('ND', 'North Dakota', false, false, null),
  ('OH', 'Ohio', false, false, null),
  ('OK', 'Oklahoma', false, false, null),
  ('OR', 'Oregon', false, false, null),
  ('PA', 'Pennsylvania', false, false, null),
  ('RI', 'Rhode Island', false, false, null),
  ('SC', 'South Carolina', false, false, null),
  ('SD', 'South Dakota', false, false, null),
  ('TN', 'Tennessee', false, false, null),
  ('TX', 'Texas', false, false, null),
  ('UT', 'Utah', true, true, now()),
  ('VT', 'Vermont', false, false, null),
  ('VA', 'Virginia', false, false, null),
  ('WA', 'Washington', false, false, null),
  ('WV', 'West Virginia', false, false, null),
  ('WI', 'Wisconsin', false, false, null),
  ('WY', 'Wyoming', false, false, null)
on conflict (code) do update
set
  name = excluded.name,
  dmv_supported = excluded.dmv_supported,
  resources_supported = excluded.resources_supported,
  verified_at = coalesce(public.us_states.verified_at, excluded.verified_at),
  updated_at = now();
